services:
    # PHP-FPM Service
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                user: headless-cms
                uid: 1000
        image: headless-cms
        container_name: headless-cms
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - headless-cms-backend

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: headless-cms-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - headless-cms-backend

    # MariaDB Service
    mariadb:
        image: mariadb:10.6
        container_name: headless-cms-mariadb
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - headless-cms-backend

    # Redis Service
    redis:
        image: redis:alpine
        container_name: headless-cms-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
        networks:
            - headless-cms-backend

    # MailHog Service
    mailhog:
        image: mailhog/mailhog
        container_name: headless-cms-mailhog
        restart: unless-stopped
        ports:
            - "1025:1025" # SMTP
            - "8025:8025" # Web UI
        networks:
            - headless-cms-backend

# Docker Networks
networks:
    headless-cms-backend:
        driver: bridge

# Docker Volumes
volumes:
    mariadb:
        driver: local
    redis:
        driver: local
    minio:
        driver: local
